name = "Porcupine"
uuid = "3b53a3d7-3f34-4bba-8df2-4717a8b1e972"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "0.1.19"

[deps]
ArrayPadding = "fe5ef43c-4912-423d-9170-4bd5cb6a013a"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ArrayPadding = "0.1"
ChainRulesCore = "1.24.0"
DataStructures = "0.18"
LinearAlgebra = "1.9"
StatsBase = "0.34.3"
UnPack = "1.0"
julia = "1.9"
