name = "Porcupine"
uuid = "3b53a3d7-3f34-4bba-8df2-4717a8b1e972"
authors = ["Paul Shen <pxshen@alumni.stanford.edu>"]
version = "0.1.3"

[deps]
ArrayPadding = "fe5ef43c-4912-423d-9170-4bd5cb6a013a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ArrayPadding = "0.1"
julia = "1.9"
